---

- hosts: localhost
  connection: local
  gather_facts: False
  remote_user: ubuntu

  vars: 
    key_name: ec2_ansible
    region: us-east-1
    instance_type: t2.micro
    image:
      id: ami-0557a15b87f6559cf
    security_group: sgboticario    
    count: 2 

  tasks:
    - name: create new ec2 instances
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        security_group: "{{ security_group }}"  
        count: "{{ count }}" 
        region: "{{ region }}"
        network:
          assign_public_ip: true
        state: present
        tags:
          Name: webserver
      register: ec2

    - name: ec2 info output
      debug: 
       var: ec2  
                 

