---

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:

    - name: create new EC2 instances
      amazon.aws.ec2_instance:
        key_name: my_keypair
        instance_type: t2.micro
        image_id: ami-0557a15b87f6559cf
        security_group: sgboticario  
        exact_count: 2 
        region: us-east-1
        network:
          assign_public_ip: true
        state: present
        tags:
          Name: webserver
                 

