---

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:

    - name: create new security group
      amazon.aws.ec2_security_group:
        name: sgboticario
        description: sg with ssh and http ruler
        vpc_id: vpc-06a65d1619d3b81eb
        profile: default
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80


