---

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:

    - name: create new EC2 instances
      amazon.aws.ec2_instance:
        key_name: "my_keypair"
        instance_type: t2.micro
        image_id: ami-0557a15b87f6559cf
        count: 2 
        region: us-east-1
        network:
          assign_public_ip: true
          security_group: sgboticario
        state: present
        tags:
                 

