---

- hosts: all
  become: True
  tasks:

  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      cache_valid_time: 3600
      
  - name: enable
    ansible.builtin.systemd:
      name: nginx
      enabled: True
  
  - name: configure index html
    ansible.builtin.template:
      src: template.j2
      dest: /var/www/html/index.html
      mode: 0644

  - name: restrart ninx
    ansible.builtin.systemd:
      name: nginx
      state: restarted      
